### ISSUE TITLE
Meta image not appearing

### ISSUE THREAD

**Issue by Sam-Varghese** [Sam-Varghese/portfolio-SamVarghese#6]
I don't know why but the meta image is not getting loaded

![image](https://user-images.githubusercontent.com/79152648/150633535-5e99fdf4-c3fe-46a7-8b7a-62102116aac7.png)

Only the meta description appears, even though I've put a meta img tag

![image](https://user-images.githubusercontent.com/79152648/150633584-3ed30c16-3028-4e76-be52-43d4c41e533f.png)

Can anybody kindly help me out

Regards
Sam Varghese

**Comment by zaidmukaddam** [comment]
There is a default way to use images from the public folder. Try using this
```html
<meta
      property="og:image"
      content="%PUBLIC_URL%/img.png"
 />
```
Also put %PUBLIC_URL% for all the files and images your are using from the public folder.
Hope this helps ✌🏻

**Comment by Sam-Varghese** [comment]
> There is a default way to use images from the public folder. Try using this
> 
> ```
> <meta
>       property="og:image"
>       content="%PUBLIC_URL%/img.png"
>  />
> ```
> 
> Also put %PUBLIC_URL% for all the files and images your are using from the public folder. Hope this helps ✌🏻

Thanks for helping! 

I changed the tag but the meta image still doesn't appear. Here's a ss of the same

![image](https://user-images.githubusercontent.com/79152648/150712927-71ac604c-3099-4d57-ba3d-c513280affbd.png)

![image](https://user-images.githubusercontent.com/79152648/150712973-9df172da-ed46-4075-b109-aaefdbd1235c.png)

Is there anything I've done incorrectly 🤔?

**Comment by zaidmukaddam** [comment]
Try resizing the image to 1200x630px.
